[project]
name = "yetanotherquant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "septem9907", email = "septem9907@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
yetanotherquant = "yetanotherquant:main"

[build-system]
requires = ["uv_build>=0.11.21,<0.12.0"]
build-backend = "uv_build"
